### ISSUE TITLE
Got Some error while registering new User

### ISSUE THREAD

**Issue by dhruvangg** [hvalls/node-firebase-auth-example#1]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
</head>
<body>
<pre>Error: Firebase.createUser failed: First argument must contain the key &quot;email&quot; with type &quot;string&quot;<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at rg (E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\firebase\lib\firebase-node.js:130:331)<br> &nbsp; &nbsp;at X.re (E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\firebase\lib\firebase-node.js:272:109)<br> &nbsp; &nbsp;at Object.addUser (E:\xampp\htdocs\node\firebase\node-firebase-auth\user_service.js:7:14)<br> &nbsp; &nbsp;at E:\xampp\htdocs\node\firebase\node-firebase-auth\server.js:12:14<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\express\lib\router\route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\express\lib\router\route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at E:\xampp\htdocs\node\firebase\node-firebase-auth\node_modules\express\lib\router\index.js:281:22</pre>
</body>
</html>

**Comment by gualbysoca** [comment]
I've got the same propblem. Did you fix It?

**Comment by nateshmbhat** [comment]
He is using a wrong method for creating User . 
If you are requiring "firebase" , you can only use client side methods . 
His code should not be `createUser` instead , it should have been `CreateUserWithEmailAndPassword` .

The create user is accessable only after requiring "firebase-admin" at the server side code .
